# -*- coding: utf-8 -*-
"""Sistema de Guía de Estudio Interactiva

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEsORHq8JNTdgNAzXWwGeXB3AipveiNH

Este primer script ejecutara el examen y a su ves guardara las respuestas de cada alumno
"""

import csv
import random
import os
from abc import ABC, abstractmethod
from datetime import datetime
import pandas as pd


# ==========================================
# 1. CLASES EN ORIENTACIÓN A OBJETOS (POO)
# ==================
class Pregunta(ABC):
    """Clase abstracta obligatoria para la estructura de una pregunta."""
    def __init__(self, enunciado, opciones, correctas):
        self.enunciado = enunciado
        self.opciones = opciones
        self.correctas = correctas  # Lista de strings limpios (ej: ['1'] o ['1', '2'])

    @abstractmethod
    def evaluar(self, respuestas_usuario):
        """Método abstracto que heredarán las clases hijas."""
        pass


class OpcionMultiple(Pregunta):
    """Pregunta tipo 'multiple': 3 opciones, 1 correcta (1 pt o 0 pts)."""
    def evaluar(self, respuestas_usuario):
        # Si responde exactamente la única opción correcta
        if len(respuestas_usuario) == 1 and respuestas_usuario[0] in self.correctas:
            return 1.0
        return 0.0


class SeleccionMultiple(Pregunta):
    """Pregunta tipo 'seleccion': 4 opciones, 2 correctas (1, 0.5 o 0 pts)."""
    def evaluar(self, respuestas_usuario):
        # Si selecciona 0 opciones o más de 2 -> 0 puntos automáticamente
        if len(respuestas_usuario) == 0 or len(respuestas_usuario) >= 3:
            return 0.0

        # Contar aciertos y errores
        correctas_elegidas = sum(1 for r in respuestas_usuario if r in self.correctas)
        incorrectas_elegidas = len(respuestas_usuario) - correctas_elegidas

        # Si seleccionó aunque sea una opción incorrecta -> 0 puntos totales
        if incorrectas_elegidas > 0:
            return 0.0

        # Si seleccionó las 2 correctas -> 1 punto completo
        if correctas_elegidas == 2:
            return 1.0
        # Si seleccionó solo una correcta y ninguna incorrecta -> 0.5 puntos
        elif correctas_elegidas == 1:
            return 0.5

        return 0.0


class Intento:
    """Guarda el número de intento y su calificación."""
    def __init__(self, numero, calificacion):
        self.numero = numero
        self.calificacion = calificacion


class Alumno:
    """Clase que representa al alumno y sus intentos (Composición)."""
    def __init__(self, nombre, materia):
        self.nombre = nombre
        self.materia = materia
        self.intentos = []

    def agregar_intento(self, calificacion):
        if len(self.intentos) < 3:
            num_intento = len(self.intentos) + 1
            self.intentos.append(Intento(num_intento, calificacion))
        else:
            raise ValueError("Ya se realizaron los 3 intentos máximos.")

    @property
    def mejor_calificacion(self):
        if not self.intentos:
            return 0.0
        return max(intento.calificacion for intento in self.intentos)


# ==========================================
# 2. PROCESAMIENTO DE ARCHIVOS CSV
# ==========================================

def cargar_banco_preguntas(ruta_csv):
    """Lee tu archivo CSV adaptándose exactamente a tus columnas."""
    banco = []
    try:
        with open(ruta_csv, mode='r', encoding='utf-8') as archivo:
            lector = csv.DictReader(archivo)
            for fila in lector:
                tipo = fila['tipo'].strip().lower()
                enunciado = fila['pregunta'].strip()

                # Cargar opciones 1, 2 y 3
                opciones = {
                    '1': fila['opcion1'].strip(),
                    '2': fila['opcion2'].strip(),
                    '3': fila['opcion3'].strip()
                }
                # Cargar opción 4 si existe
                if fila.get('opcion4') and fila['opcion4'].strip():
                    opciones['4'] = fila['opcion4'].strip()

                # Separar las respuestas correctas por el punto y coma ';' de tu archivo
                correctas = [str(c.strip()) for c in fila['correcta'].split(';') if c.strip()]

                # Instanciar según el tipo de tu archivo
                if tipo == 'multiple':
                    if '4' in opciones: opciones.pop('4', None) # Forzar 3 opciones
                    banco.append(OpcionMultiple(enunciado, opciones, correctas))
                elif tipo == 'seleccion':
                    banco.append(SeleccionMultiple(enunciado, opciones, correctas))

    except FileNotFoundError:
        print(f"\n[ERROR]: No se encontró el archivo '{ruta_csv}' en el panel izquierdo.")
        return None
    return banco


def guardar_resultados_csv(alumno, ruta_resultados):
    """Guarda las calificaciones finales en 'resultados.csv'."""
    calificaciones_intentos = [0.0, 0.0, 0.0]
    for i, intento in enumerate(alumno.intentos):
        calificaciones_intentos[i] = intento.calificacion

    fila = [
        alumno.nombre,
        alumno.materia,
        calificaciones_intentos[0],
        calificaciones_intentos[1],
        calificaciones_intentos[2],
        alumno.mejor_calificacion,
        datetime.now().strftime("%Y-%m-%d")
    ]

    es_nuevo = not os.path.exists(ruta_resultados)
    with open(ruta_resultados, mode='a', newline='', encoding='utf-8') as archivo:
        escritor = csv.writer(archivo)
        if es_nuevo:
            escritor.writerow(["Nombre completo", "Materia", "Intento1", "Intento2", "Intento3", "Calificacion final", "Fecha"])
        escritor.writerow(fila)


# ==========================================
# 3. EJECUCIÓN INTERACTIVA EN CONSOLA
# ==========================================

def ejecutar_examen():
    print("==================================================")
    print("  SISTEMA DE GUÍA DE ESTUDIO INTERACTIVA - SEGUROS ")
    print("==================================================\n")

    ruta_preguntas_csv = "preguntas_seguros_.csv"
    ruta_csv_temporal = "temp_preguntas.csv"
    ruta_resultados = "resultados.csv"

    banco_completo = []
    try:
        # Cargar el archivo CSV en un DataFrame de pandas
        df_csv = pd.read_csv(ruta_preguntas_csv, encoding='latin1') # Added encoding='latin1'
        # Guardar como CSV temporal para que la función existente pueda leerlo
        df_csv.to_csv(ruta_csv_temporal, index=False, encoding='utf-8')

        # Cargar banco de preguntas desde el CSV temporal
        banco_completo = cargar_banco_preguntas(ruta_csv_temporal)
    except FileNotFoundError:
        print(f"\n[ERROR]: No se encontró el archivo '{ruta_preguntas_csv}' en el panel izquierdo.")
        return
    finally:
        # Limpiar el archivo CSV temporal si existe
        if os.path.exists(ruta_csv_temporal):
            os.remove(ruta_csv_temporal)

    if not banco_completo:
        return

    # print(f"¡Éxito! Se cargaron {len(banco_completo)} preguntas de Seguros.\n")

    # Solicitar nombre al usuario
    nombre = input("Ingresa tu nombre completo: ").strip()
    if not nombre:
        nombre = "Invitado"
        print("No se ingresó un nombre, se usará 'Invitado'.")

    materia = "Seguros"
    print(f"Estudiante registrado: {nombre}")
    print(f"Materia: {materia}\n")

    estudiante = Alumno(nombre, materia)

    # Ciclo de los 3 intentos
    for num_intento in range(1, 4):
        print(f"--- INICIANDO INTENTO {num_intento} DE 3 ---")

        # Seleccionar 10 preguntas aleatorias sin repetir en este intento
        preguntas_intento = random.sample(banco_completo, 10)
        puntaje_acumulado = 0.0

        for i, pregunta in enumerate(preguntas_intento, start=1):
            print(f"\nPregunta {i}: {pregunta.enunciado}")
            for clave, texto in pregunta.opciones.items():
                print(f"  {clave}) {texto}")

            while True:
                entrada_usuario = input("Tu respuesta: ")

                respuestas_usuario = []
                if entrada_usuario:
                    for parte in entrada_usuario.split(','):
                        parte_limpia = str(parte.strip())
                        if parte_limpia:
                            respuestas_usuario.append(parte_limpia)

                # Verificar que todas las respuestas existan en las opciones
                if all(r in pregunta.opciones for r in respuestas_usuario):
                    break
                else:
                    print("¡Opción no válida! Intenta nuevamente.")

            # Evaluar y sumar puntaje
            puntos = pregunta.evaluar(respuestas_usuario)
            puntaje_acumulado += puntos
            print(f"-> Puntos en esta pregunta: {puntos}")

        # Guardar intento terminado
        estudiante.agregar_intento(puntaje_acumulado)
        print(f"\n>>> Fin del Intento {num_intento}. Calificación obtenida: {puntaje_acumulado} / 10.0 <<<\n")

        if num_intento < 3:
          while True:
              otra_vez = input("¿Quieres hacer otro intento? (Si/No): ").strip().upper()

              if otra_vez == "NO":
                  break
              elif otra_vez == "SI":
                  # Sale del while y continúa con el siguiente intento
                  break
              else:
                  print("¡Respuesta no válida!\n")

          if otra_vez == "NO":
              break

        else:
            print("Has completado tus 3 intentos permitidos.")

    # Guardar reporte histórico en el CSV externo
    guardar_resultados_csv(estudiante, ruta_resultados)

    print("\n==================================================")
    print("                REPORTE FINAL                     ")
    print("==================================================")
    print(f"Nombre:           {estudiante.nombre}")
    print(f"Materia:          {estudiante.materia}")
    print(f"Intentos hechos:  {len(estudiante.intentos)}")
    for intento in estudiante.intentos:
        print(f"  - Calificación Intento {intento.numero}: {intento.calificacion}")
    print(f"Calificación Final (Mejor Intento): {estudiante.mejor_calificacion}")
    print("==================================================")
    # print("¡Resultados guardados con éxito en 'resultados.csv'!")

# Arrancar el programa
ejecutar_examen()

"""Este segundo script generara el reporte estadistico"""

def generar_reporte_estadistico(ruta_csv="resultados.csv"):
    """
    Lee el archivo de resultados CSV y calcula las estadísticas requeridas
    por la rúbrica del proyecto final.
    """
    print("=" * 50)
    print("        SISTEMA DE REPORTES ESTADÍSTICOS        ")
    print("=" * 50)

    if not os.path.exists(ruta_csv):
        print(f"⚠️ Error: El archivo '{ruta_csv}' no existe todavía.")
        print("Asegúrate de que al menos un alumno haya terminado el examen para generar datos.")
        return

    total_estudiantes = 0
    suma_calificaciones_finales = 0.0

    calificaciones_por_materia = {}
    calificaciones_por_fecha = {}

    mejor_estudiante = ""
    mejor_calificacion = -1.0

    try:
        with open(ruta_csv, mode='r', encoding='utf-8') as archivo:
            lector = csv.DictReader(archivo)

            for fila in lector:
                total_estudiantes += 1

                nombre = fila["Nombre completo"]
                materia = fila["Materia"]
                fecha = fila["Fecha"].split()[0]
                calif_final = float(fila["Calificacion final"])

                suma_calificaciones_finales += calif_final

                if materia not in calificaciones_por_materia:
                    calificaciones_por_materia[materia] = []
                calificaciones_por_materia[materia].append(calif_final)

                if fecha not in calificaciones_por_fecha:
                    calificaciones_por_fecha[fecha] = []
                calificaciones_por_fecha[fecha].append(calif_final)

                if calif_final > mejor_calificacion:
                    mejor_calificacion = calif_final
                    mejor_estudiante = nombre

        if total_estudiantes == 0:
            print("🛑 El archivo CSV está vacío. No hay alumnos registrados.")
            return

        # Define promedio_general before its usage
        promedio_general = suma_calificaciones_finales / total_estudiantes

        print(f"✔️ Número total de estudiantes evaluados: {total_estudiantes}")
        print(f"✔️ Promedio general de calificaciones: {promedio_general:.2f} / 10.0")

        print("\n📊 Promedio por Materia:")
        for mat, lista_califs in calificaciones_por_materia.items():
            prom_mat = sum(lista_califs) / len(lista_califs)
            print(f"   - {mat}: {prom_mat:.2f}")

        print("\n📅 Promedio por Fecha de Evaluación:")
        for fec, lista_califs in calificaciones_por_fecha.items():
            prom_fec = sum(lista_califs) / len(lista_califs)
            print(f"   - {fec}: {prom_fec:.2f}")

        print("\n🏆 Rendimiento Destacado:")
        print(f"   - Mejor estudiante: {mejor_estudiante} (Calificación: {mejor_calificacion:.2f})")
        print("=" * 50)

    except KeyError as e:
        print(f"❌ Error de formato en el CSV: Falta la columna {e}.")
    except ValueError:
        print("❌ Error: Se encontraron datos numéricos corruptos en las calificaciones.")
    except Exception as e:
        print(f"❌ Ocurrió un error inesperado al procesar el reporte: {e}")

if __name__ == "__main__":
    generar_reporte_estadistico()